#!/bin/bash
sudo apt-get update
yes | sudo apt-get upgrade
sudo apt-get -y install  libi2c-dev i2c-tools python-smbus libfuse-dev python-pil
git clone https://github.com/Percheron-Electronics/gratis2 gratis
cd gratis
make rpi
sudo make rpi-install
sudo reboot


